FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 5000

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["Pro-crud-mudblazor.csproj",""]
RUN dontet restore "./Pro-crud-mudblazor.csproj"
COPY . .
WORKDIR "/src"
RUN dotnet build "Pro-crud-mudblazor.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Pro-crud-mudblazor.csproj" -c Release -o /app/publish


# final stage/image
FROM base AS final
WORKDIR /app
COPY --from=build /app ./
ENTRYPOINT ["dotnet", "Pro-crud-mudblazor.dll"]

